# It contains all the configs required in the project

data:  
  url: "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip"
  local_dir: data
  data_file: data.zip
  unzip_data_dir: input_images            ## In future if we want we can store the extracted data in some other location.
  bad_data_dir: bad_data
  parent_data_dir: PetImages
  model_dir_path: model
  init_model_name: model.h5

params:
  learning_rate: 0.01
  img_shape: [180,180,3]     ## we have to use in square brackets and then convert them into the tuple while reading those in base creation
  loss: sparse_categorical_entropy
  metrics: ["accuracy"]
    